spring.application.name=posts-service
spring.datasource.url=${POSTS_DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update

server.port=8081
management.endpoints.web.exposure.include=prometheus
